### ISSUE TITLE
config file doesnt load in

### ISSUE THREAD

**Issue by RisenID** [alexandreteles/jmusicbot-docker#1]
![Screenshot 2022-01-23 150922](https://user-images.githubusercontent.com/94130108/150673057-124dfcad-1395-4bdb-a9cc-eb9c6368e8bc.png)

Commands tried and error. Path is correct and config and server settinsg file are in that folder. Same issue faced even if command prompt is used.

**Comment by alexandreteles** [comment]
Dammit. The documentation points to the wrong image, that's why you're having problems running it. The image should be `alexandreteles/jmusicbot` instead of `jagrosh/jmusicbot` as jagrosh himself doesn't provide a docker image even if we insist on having an official one. Anyway, your problem should be solved if you run:

```sh
docker run --name jmusicbot -d -v /home/rawr/.docker/desktop/config.txt:/app/config.txt:ro -v /home/rawr/.docker/desktop/serversettings.json:/app/serversettings.json:ro --restart=always alexandreteles/jmusicbot
```

I'm closing this issue just so I can keep track of what I'm doing but feel free to reopen it if needed.
